---
Name: ralph-routes
After: 'framework/*', 'cms/*'
---
DevelopmentAdmin:
  registered_controllers:
    ralph:
      controller: 'SilbinaryWolf\Ralph\DevAdmin'
      links:
        ralph: 'Debug database data with a GridField view'
